/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            fontFamily: {
                inter: ['Inter var', 'sans-serif'],
                roboto_flex: ['Roboto flex', 'sans-serif'],
            },
            colors: {},
        },
        screens: {
            phone: '320px',
            tablet: '640px',
            laptop: '1024px',
            desktop: '1280px',
        },
    },
    plugins: [require('daisyui')],
    daisyui: {
        styled: true,
        themes: [
            'light',
            'dark',
            'cupcake',
            'bumblebee',
            'emerald',
            'corporate',
            'synthwave',
            'retro',
            'cyberpunk',
            'valentine',
            'halloween',
            'garden',
            'forest',
            'aqua',
            'lofi',
            'pastel',
            'fantasy',
            'wireframe',
            'black',
            'luxury',
            'dracula',
            'cmyk',
            'autumn',
            'business',
            'acid',
            'lemonade',
            'night',
            'coffee',
            'winter',
            {
                neon: {
                    primary: '#8b5cf6',
                    secondary: '#e879f9',
                    accent: '#f9a8d4',
                    neutral: '#191D24',
                    'base-100': '#111827',
                    info: '#67e8f9',
                    success: '#6ee7b7',
                    warning: '#fcd34d',
                    error: '#fca5a5',
                },
            },
        ],
        base: true,
        utils: true,
        logs: true,
        rtl: false,
        prefix: '',
        darkTheme: 'dark',
    },
};
