export const themes = [
    { value: 'system', option: 'System' },
    { value: 'light', option: 'Light' },
    { value: 'dark', option: 'Dark' },
    { value: 'neon', option: 'Neon' },
    { value: 'cupcake', option: 'Cupcake' },
    { value: 'bumblebee', option: 'Bumblebee' },
    { value: 'emerald', option: 'Emerald' },
    { value: 'corporate', option: 'Corporate' },
    { value: 'synthwave', option: 'Synthwave' },
    { value: 'retro', option: 'Retro' },
    { value: 'cyberpunk', option: 'Cyberpunk' },
    { value: 'valentine', option: 'Valentine' },
    { value: 'halloween', option: 'Halloween' },
    { value: 'garden', option: 'Garden' },
    { value: 'forest', option: 'Forest' },
    { value: 'aqua', option: 'Aqua' },
    { value: 'lofi', option: 'Lofi' },
    { value: 'pastel', option: 'Pastel' },
    { value: 'fantasy', option: 'Fantasy' },
    { value: 'wireframe', option: 'Wireframe' },
    { value: 'black', option: 'Black' },
    { value: 'luxury', option: 'Luxury' },
    { value: 'dracula', option: 'Dracula' },
    { value: 'cmyk', option: 'Cmyk' },
    { value: 'autumn', option: 'Autumn' },
    { value: 'business', option: 'Business' },
    { value: 'acid', option: 'Acid' },
    { value: 'lemonade', option: 'Lemonade' },
    { value: 'night', option: 'Night' },
    { value: 'coffee', option: 'Coffee' },
    { value: 'winter', option: 'Winter' },
];

// export const lengths = [{ option: 'Nanometers' }];
